### ISSUE TITLE
Issue with dig and resolver1.opendns.com

### ISSUE THREAD

**Issue by chatainsim** [brianpcurran/gandi-automatic-dns#12] opened 2015-12-17 15:43 UTC
Hello,

I have an issue with your script:
```
dig: couldn't get address for 'resolver1.opendns.com': not found
Failed to determine external IP address with OpenDNS. See above error.
```
Can you help me with this ?

Thanks

**Comment by brianpcurran** [comment] 2015-12-17 15:57
What OS are you running?

**Comment by chatainsim** [comment] 2015-12-17 17:28
Hello,
I'm running Ubuntu 12.04.5:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:        12.04
Codename:       precise
```
And I'm using Google DNS servers:
```
$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by brianpcurran** [comment] 2015-12-17 20:37
I'm unable to reproduce this. What does "dig @8.8.8.8 resolver1.opendns.com" output?

Alternately, if OpenDNS isn't working for you for some reason, you could try using the -s flag and piping "curl ipinfo.io/ip" to your gad command.

**Comment by chatainsim** [comment] 2015-12-17 22:27
Here is the dig command:
```
$ dig @8.8.8.8 resolver1.opendns.com

; <<>> DiG 9.8.1-P1 <<>> @8.8.8.8 resolver1.opendns.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14625
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;resolver1.opendns.com.         IN      A

;; ANSWER SECTION:
resolver1.opendns.com.  561     IN      A       208.67.222.222

;; Query time: 62 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Dec 17 23:26:39 2015
;; MSG SIZE  rcvd: 55
```

Yes, for now I'm using the curl piping to gad.

**Comment by brianpcurran** [comment] 2015-12-18 15:10
Can you try without the -s flag again? It looks like there was an intermittent issue with resolving resolver1.opendns.com but that last dig command was successful, so it should work now.

**Comment by brianpcurran** [comment] 2016-01-10 05:00
I'm going to close this. If you're still having issues let me know.

**Closed by brianpcurran** 2016-01-10 05:00 UTC
